In [1]:
pip list


Package              Version
-------------------- -----------
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.8
attrs                22.1.0
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.1
cffi                 1.15.1
colorama             0.4.5
debugpy              1.6.3
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
executing            1.0.0
fastjsonschema       2.16.1
ipykernel            6.15.2
ipython              8.4.0
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.1.2
jsonschema           4.15.0
jupyter_client       7.3.5
jupyter-core         4.11.1
jupyterlab-pygments  0.2.2
lxml                 4.9.1
MarkupSafe           2.1.1
matplotlib-inline    0.1.6
mistune              2.0.4
nbclient             0.6.7
nbconvert            7.0.0
nbformat             5.4.0
nest-asyncio         1.5.5
notebook             6.4.12
numpy                1.23.2
packaging 

In [4]:
!pip install numpy


  Using cached numpy-1.23.2-cp310-cp310-win_amd64.whl (14.6 MB)


In [5]:
import numpy as np

In [6]:
kanto = np.array([73,67,43])

In [7]:
kanto

array([73, 67, 43])

In [17]:
weights = np.array([0.3,0.2,0.5])

In [9]:
type(kanto)

numpy.ndarray

In [14]:
%%time 
np.dot(kanto, weights)

CPU times: total: 0 ns
Wall time: 0 ns


56.8

In [11]:
kanto*weights

array([21.9, 13.4, 21.5])

In [12]:
(kanto*weights).sum()

56.8

In [22]:
import urllib.request as rq

rq.urlretrieve(
'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',"climate.txt")

('climate.txt', <http.client.HTTPMessage at 0x1b3bc502b90>)

In [23]:
climate_data = np.genfromtxt("climate.txt",delimiter=",",skip_header = 1)

In [24]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [26]:
climate_data.shape

(10000, 3)

In [27]:
weights = np.array([0.3,0.2,0.5])

In [28]:
yeilds = climate_data @ weights

In [29]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [30]:
yeilds.shape

(10000,)

In [31]:
results = np.concatenate((climate_data, yeilds.reshape(10000,1)),axis = 1)

In [32]:
results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [33]:
np.savetxt('climate_results.txt',results,fmt='%.2f',header='temperature,rainfall,humidity,yeild_apples',comments='')